.toxTable_cycle = function(toxDB , cycles){

  if (toxDB@options@discardBaseline) {
    toxDB@cleanData = toxDB@cleanData[toxDB@cleanData$occur_in_cycle_1 == 0, ]
  }

  # print all permitted data
  if(cycles == "all") {
    cycles = 1:length(toxDB@cycleLabels)
  }

  #####################################################################
  # subset database with toxicities in requested cycles cycles
  toxDB@cleanData$x = apply(toxDB@cleanData[paste0("occur_in_cycle_", cycles)] , 1 , function(y) max(as.numeric(y)))
  cleanDataSub = toxDB@cleanData[toxDB@cleanData$x > 0 & toxDB@cleanData$ass_TRUE, ]

  # maximum cycle must go up to
  max.cycle = sum(str_detect(names(cleanDataSub), "occur_in_cycle_"))
  # names of the cycles
  names_occur = names(cleanDataSub)[str_detect(names(cleanDataSub), "occur_in_cycle_")]


  treats = sort(unique(toxDB@cleanData$treatment))


  # generate initial table
  if(toxDB@options@tabulationMethod == "worst"){
    toxTable = .toxTable_worst(cleanDataSub, treats)
  } else if(toxDB@options@tabulationMethod == "all"){
    toxTable = .toxTable_all(cleanDataSub, treats)
  }


  nPatients = rep(0, length(treats))
  # count and record number of patients having at least some of the required time period (saved in nPatients)



  for(treatment in 1:length(treats)){
    # number of patients at this cycle
    tox_s = toxDB@cleanData[toxDB@cleanData$treatment == treats[treatment], ]
    if(length(cycles)>1){
      nPatients[treatment] = length(unique(tox_s$patid[apply(tox_s[, paste0("present_in_cycle_", cycles)], 1, function(x) sum(x) > 0)]))
    } else {
      nPatients[treatment] = length(unique(tox_s$patid[tox_s[, paste0("present_in_cycle_", cycles)]]))
    }
  }

  # Perform the column merge for toxicities
  if(is.null(toxDB@options@cycleColumnMerge) == FALSE){
    colMerge = strsplit(toxDB@options@cycleColumnMerge, "[|]")[[1]]
    toxTableClean = data.frame(toxID = toxTable$toxID, category = toxTable$category, toxicity = toxTable$toxicity, stringsAsFactors = FALSE)
    for(side in 1:length(treats)){
      for(col in colMerge){
        if(toxDB@options@cumulativeGrades) {

          composition = min(as.numeric(strsplit(col, ",")[[1]])):5
          cols = paste0("tox.", side, ".", composition)
          cname = paste0("tox.", side, ".", composition[1])
          if(length(composition) > 1) {
            toxTableClean[, cname] = apply(toxTable[, cols], 1, function(x) {sum(as.numeric(x), na.rm = TRUE)})
          } else {
            toxTableClean[, cname] = toxTable[, cols]
          }

        } else {

          composition = as.numeric(strsplit(col, ",")[[1]])
          cols = paste0("tox.", side, ".", composition)
          cname = paste0("tox.", side, ".", paste0(composition, collapse = ""))
          if(length(composition) > 1) {
            toxTableClean[, cname] = apply(toxTable[, cols], 1, function(x) {sum(as.numeric(x), na.rm = TRUE)})
          } else {
            toxTableClean[, cols] = toxTable[, cols]
          }
        }
      }
    }
    toxTable = toxTableClean
  }

  # Order according to toxID (ensuring that the toxicities are ordered alphabetically first by category and then by toxicity)
  toxTable = toxTable[order(as.numeric(as.character(toxTable$toxID)), decreasing = FALSE), ]
  toxTable = toxTable[which(toxTable$toxicity!= ""), ]
  # Perform the row merge for categories
  if(length(toxDB@options@cycleCategoryMerge)){
    for(category in toxDB@options@cycleCategoryMerge){
      if(category != ""){
        if(category %in% toxTable$category){
          merge.rows = which(category == toxTable$category)
          di = dim(toxTable)
          toxTable[merge.rows[1], 4:di[2]] = apply(toxTable[merge.rows, 4:di[2]], 2, function(x) {sum(as.numeric(x))})
          toxTable$toxicity[merge.rows[1]] = ""
          if(length(merge.rows)>1){
            toxTable = toxTable[-merge.rows[2:length(merge.rows)], ]
          }
        }
      }
    }
  }


  # drop toxID as not needed after ordering
  toxTable$toxID = NULL

  # remove duplication of writing categories (one under the other before)
  a = dim(toxTable)[1]
  if(a >= 3){
    for(i in a:2){
      if(toxTable$category[i-1] == toxTable$category[i]){
        toxTable$category[i] = ""
      }
    }
  }

  # renaming
  colnames(toxTable)[1:2] = c("Category", "Toxicity")

  # return the table to the app
  return(list(toxTable=toxTable, nPatients=nPatients))
}

# end




.toxTable_worst = function (toxDB, treatments) {


  # create table to populate
  toxTable = .toxTableSetup(length(treatments))
  dm = dim(toxTable)

  i = 0
  toxID = sort(unique(toxDB$ass_toxID)) # note ass_toxID is generated by prepareToxicity
  for(tox in toxID){

    toxDB_2 = toxDB[toxDB$ass_toxID == tox,]
    i = i + 1
    # ID, category and name of toxicity
    toxTable[i,1:3] = c(tox, toxDB_2$ass_category[1], toxDB_2$ass_toxicity_disp[1])
    toxTable[i,4:dm[2]] = rep(0, length(treatments) * 5)

    # by treatment add data
    for(treatment in 1:length(treatments)) {
      toxDB_3 = toxDB_2[toxDB_2$treatment == treatments[treatment],]
      # aggregate for each patient taking the maximum grade
      if(dim(toxDB_3)[1]>0) {
        x = aggregate(toxDB_3$x, by = list(toxDB_3$patid), FUN = max)$x
        toxTable[i,4:8 + (treatment - 1) * 5] = c(sum(x == 1), sum(x == 2), sum(x == 3), sum(x == 4), sum(x == 5))
      } else {
        toxTable[i,4:8 + (treatment - 1) * 5] = rep(0, 5)
      }
    }
  }

  return(toxTable)
}

.toxTable_all=function(toxDB,treatments){


  # create table to populate
  toxTable = .toxTableSetup(length(treatments))
  print(toxTable)
  i=0
  toxID=sort(unique(toxDB$ass_toxID))
  for (tox in toxID) {
    toxDB_2 = toxDB[toxDB$ass_toxID == tox, ]
    i = i + 1
    # ID, category and name of toxicity
    toxTable[i, 1:3] = c(tox, toxDB_2$ass_category[1], toxDB_2$ass_toxicity_disp[1])
    toxTable[i, 3 + 1:(length(treatments) * 5)] = 0
    # by treatment add data
    for (treatment in 1:length(treatments)) {
      toxDB_3 = toxDB_2[toxDB_2$treatment == treatments[treatment], ]
      # aggregate for each patient taking the maximum grade
      if (dim(toxDB_3)[1] > 0) {
        # add to table
        toxTable[i, 4:8 + (treatment - 1) * 5]=c(sum(toxDB_3$x == 1), sum(toxDB_3$x == 2), sum(toxDB_3$x == 3), sum(toxDB_3$x == 4), sum(toxDB_3$x == 5))
      } else {
        toxTable[i, 4:8 + (treatment-1) * 5]= rep(0, 5)
      }
    }
  }

  return(toxTable)
}



.toxTableSetup = function(noTreatments) {

  # create table to populate
  toxTable=data.frame(toxID=rep(0,1), category=rep("",1), toxicity=rep("",1), stringsAsFactors = FALSE)
  for(side in 1:noTreatments){
    toxTable[paste0("tox.", side,".1", sep = "")]= 0
    toxTable[paste0("tox.", side,".2", sep = "")]= 0
    toxTable[paste0("tox.", side,".3", sep = "")]= 0
    toxTable[paste0("tox.", side,".4", sep = "")]= 0
    toxTable[paste0("tox.", side,".5", sep = "")]= 0
  }
  return(toxTable[0,])
}

