


#' Table: Worst toxicity
#'
#'
#'
#' @inheritParams prepareToxicity
#' @param treatments vector of treatments

#' @export toxTable_worst

toxTable_worst = function (toxDB, treatments) {


  # create table to populate
  toxTable = .toxTableSetup(length(treatments))
  dm = dim(toxTable)

  i = 1
  toxID = sort(unique(toxDB$ass_toxID)) # note ass_toxID is generated by prepareToxicity
  for(tox in toxID){

    toxDB_2 = toxDB[toxDB$ass_toxID == tox,]
    i = i + 1
    # ID, category and name of toxicity
    toxTable[i,1:3] = c(tox, toxDB_2$ass_category[1], toxDB_2$ass_toxicity_disp[1])
    toxTable[i,4:dm[2]] = rep(0, length(treatments) * 5)

    # by treatment add data
    for(treatment in 1:length(treatments)) {
      toxDB_3 = toxDB_2[toxDB_2$treatment == treatments[treatment],]
      # aggregate for each patient taking the maximum grade
      if(dim(toxDB_3)[1]>0) {
        x = aggregate(toxDB_3$x, by = list(toxDB_3$patid), FUN = max)$x
          toxTable[i,4:8 + (treatment - 1) * 5] = c(sum(x == 1), sum(x == 2), sum(x == 3), sum(x == 4), sum(x == 5))
      } else {
        toxTable[i,4:8 + (treatment - 1) * 5] = rep(0, 5)
      }
    }
  }

  return(toxTable)
}
